# Main Window constants
MAIN_GRID_HEIGHT = 8
MAIN_GRID_WIDTH = 8

MAIN_GRID_CLEAR_HEIGHT_POSITION = 1
MAIN_GRID_CLEAR_WIDTH_POSITION = MAIN_GRID_WIDTH + 2

MAIN_GRID_SOLVE_HEIGHT_POSITION = 3
MAIN_GRID_SOLVE_WIDTH_POSITION = MAIN_GRID_WIDTH + 2

MAIN_GRID_DEBUG_BUTTON_HEIGHT_POSITION = 5
MAIN_GRID_DEBUG_BUTTON_WIDTH_POSITION = MAIN_GRID_WIDTH + 2

# Engine and component window constansts
ENGINE_COMPONENT_DROPDOWN_WIDTHS = 20

REACTOR_DROPDOWN_LABEL = "Select a Reactor:"
GENERATOR_DROPDOWN_LABEL_FIRST = "Select first Generator:"
GENERATOR_DROPDOWN_LABEL_SECOND = "Select second Generator:"

# Button visuals
# On
TOGGLE_ON_GRID_BG = "green"
TOGGLE_ON_GRID_FG = "green"

# Off
TOGGLE_OFF_GRID_BG = "white"
TOGGLE_OFF_GRID_FG = "white"

# Colour array for the shape designer
SHAPE_COLOUR_ARRAY = []