
MAIN_GRID_HEIGHT = 10
MAIN_GRID_WIDTH = 10

MAIN_GRID_CLEAR_HEIGHT_POSITION = 1
MAIN_GRID_CLEAR_WIDTH_POSITION = MAIN_GRID_WIDTH + 2

MAIN_GRID_SOLVE_HEIGHT_POSITION = 3
MAIN_GRID_SOLVE_WIDTH_POSITION = MAIN_GRID_WIDTH + 2

MAIN_GRID_DEBUG_BUTTON_HEIGHT_POSITION = 5
MAIN_GRID_DEBUG_BUTTON_WIDTH_POSITION = MAIN_GRID_WIDTH + 2

# Button visuals
TOGGLE_ON_BG = "green"
TOGGLE_ON_FG = "green"

TOGGLE_OFF_BG = "white"
TOGGLE_OFF_FG = "white"
